title: <p align="center">Susmita Banik</p>
logo: /assets/img/passport_size_photo.jpeg
description: 14+ years with Project Management & Agile Enthusiast | AI/ML Enthusiast | Certified Scrum Master | Believes in #OutcomeBasedDelivery #CustomerCentricity #TeamWork
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
